apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: function-pod
  labels:
    heritage: float
  annotations:
    "float/version": {{ .Values.docker_tag }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      component: function-pod
  template:
    metadata:
      labels:
        component: function-pod
        float/version: {{ .Values.docker_tag }}    
      annotations:
        float: function-pod
    spec:
      containers:
      - name: float-function-pod
        image: "{{ .Values.repo_prefix }}shim:{{ .Values.docker_tag }}"
        imagePullPolicy: {{ .Values.pull_policy }}
        tty: false
        # livenessProbe:
        #   httpGet:
        #     path: /+/healthz
        #     port: {{ .Values.shim.port }}
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /+/readiness
        #     port: {{ .Values.shim.port }}
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        #   periodSeconds: 5
        ports:
        - containerPort: {{ .Values.shim.port }}
          name: http
        env:
        - name: IS_PROD
          value: "1"
        - name: PORT
          value: "{{ .Values.shim.port }}"