kind: Service
apiVersion: v1
metadata:
  name: functions
  labels:
    heritage: float
  annotations:
    float/svc: internal
spec:
  selector:
    component: function-pod
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.shim.port }}