kind: Service
apiVersion: v1
metadata:
  name: coordinator
  labels:
    heritage: float
  annotations:
    float/svc: internal
spec:
  selector:
    component: coordinator
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.coordinator.port }}